
platform :ios ,'10.0'
use_frameworks!


target 'Kamu' do

pod 'AFNetworking' 
pod 'Masonry', '~> 0.6.1’
pod 'RDVTabBarController'
#pod 'ReactiveCocoa', "2.5.0"
#pod 'ReactiveCocoaEx', '~> 4.1'
pod 'ReactiveObjC'
pod 'SpinKit', '~> 1.1'
pod 'SDWebImage', '~> 4.2'
#pod 'FFmpeg', '~> 2.8'
pod 'Realm', '~> 3.0'
pod 'MGSwipeTableCell'
pod 'JPush', '3.0.2'
pod 'MJRefresh','~>3.1'
pod 'MJExtension'
#pod 'ZFPlayer'
pod 'MMDrawerController', '~> 0.5.7'

end

#target 'Kamu' do
#    
#end

